language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - pypy
cache:
  directories:
    - $HOME/.cache/pip
matrix:
  fast_finish: true
install:
  - make setup
  - pip install coveralls

script: make ci_test

after_success:
  coveralls
